<a href="https://colab.research.google.com/github/chaitravi-ce/PyTorch_Tutorials/blob/main/Pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

## Tensors

In [ ]:
t1 = torch.tensor(4.0)
print(t1.dtype)

torch.float32


In [ ]:
t2 = torch.tensor([1., 2, 3, 4])
print(t2)

tensor([1., 2., 3., 4.])


In [ ]:
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
print(t3)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


In [ ]:
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
print(t4)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


In [ ]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


## Tensor operations and gradients

In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
# Compute derivatives
y.backward()

In [ ]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


## Torch Functions

In [ ]:
# Create a tensor with a fixed value for every element
t6 = torch.full((2, 5), 9)
t6

tensor([[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]])

In [ ]:
t7 = torch.full((4,5), 12)
torch.cat((t6,t7))

tensor([[ 9,  9,  9,  9,  9],
        [ 9,  9,  9,  9,  9],
        [12, 12, 12, 12, 12],
        [12, 12, 12, 12, 12],
        [12, 12, 12, 12, 12],
        [12, 12, 12, 12, 12]])

In [ ]:
t8 = torch.sin(t7)
t8

tensor([[-0.5366, -0.5366, -0.5366, -0.5366, -0.5366],
        [-0.5366, -0.5366, -0.5366, -0.5366, -0.5366],
        [-0.5366, -0.5366, -0.5366, -0.5366, -0.5366],
        [-0.5366, -0.5366, -0.5366, -0.5366, -0.5366]])

In [ ]:
t8.reshape((5,2,2))

tensor([[[-0.5366, -0.5366],
         [-0.5366, -0.5366]],

        [[-0.5366, -0.5366],
         [-0.5366, -0.5366]],

        [[-0.5366, -0.5366],
         [-0.5366, -0.5366]],

        [[-0.5366, -0.5366],
         [-0.5366, -0.5366]],

        [[-0.5366, -0.5366],
         [-0.5366, -0.5366]]])

## Numpy Module

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])